### ISSUE TITLE
Due diligence: Ensure TypeScript works

### ISSUE THREAD

**Issue by kaicataldo** [kaicataldo/eleventy-plugin-react#12]
I _believe_ TypeScript support should work out of the box with [`@babel/preset-typescript`](https://babeljs.io/docs/en/babel-preset-typescript), but let's confirm it does!

**Comment by dpfavand** [comment]
I am shocked at how easy this was.

I added `@babel/preset-typescript` to my project's `babelConfig()` callback, and added the `tsx` extension to the `SUPPORTED_EXTENSIONS` array. Typescript appears to "just work".

Full plugin configuration:
```js
  eleventyConfig.addPlugin(eleventyReact, {
    babelConfig({ isBrowser }) {
      return {
        presets: [
          ["@babel/preset-react"],
          ["@babel/preset-typescript"],
          [
            "@babel/preset-env",
            isBrowser
              ? {
                modules: false,
                targets: "> 0.25%, not dead",
              }
              : {
                modules: "commonjs",
                targets: {
                  node: process.versions.node,
                },
              },
          ],
        ],
      };
    },
  });
```

**Comment by dpfavand** [comment]
I think by making extensions configurable (#13) and providing a sane default Babel config (#8) this plugin can provide a pretty good just-works Typescript experience.

**Comment by kaicataldo** [comment]
Ah, right, I forgot about the supported extensions being hardcoded. Seems like we should be able to make `['js', 'jsx', 'ts', 'tsx']` supported by default, but agree that a configuration option makes sense.

**Comment by kaicataldo** [comment]
Closed by https://github.com/kaicataldo/eleventy-plugin-react/pull/15
