### ISSUE TITLE
Create a Babel preset for peer deps

### ISSUE THREAD

**Issue by kaicataldo** [kaicataldo/eleventy-plugin-react#16]
Now that https://github.com/kaicataldo/eleventy-plugin-react/pull/15 has been merged and I've decided to keep the peer deps, I'd like to create a separate preset package that can be installed to set up all the peer deps and configuration for you. This seems like the best balance of "sane defaults" while allow complete configuration for the end user.

**Comment by dpfavand** [comment]
I wonder maintaining a separate package is actually necessary? Maybe we suggest folks install this package using [install-peerdeps](https://www.npmjs.com/package/install-peerdeps)

```
npx install-peerdeps eleventy-plugin-react
```

And also note that with [NPM 7 peer dependencies will automatically be installed](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/).

**Comment by kaicataldo** [comment]
I had originally thought that this would be a nice way to allow folks to extend off the base configuration for the user, but now that we're exposing the base configuration maybe we should just let npm 7 do its thing?

**Comment by kaicataldo** [comment]
Going to close this for now - we can always revisit this in the future.
