### ISSUE TITLE
Feature: sane defaults with Babel's configuration API

### ISSUE THREAD

**Issue by kaicataldo** [kaicataldo/eleventy-plugin-react#8]
As discussed [here](https://github.com/kaicataldo/eleventy-plugin-react/issues/4#issuecomment-707437685), the original intention (and first iteration) of this plugin kept all the Babel configuration under the hood (Babel and co as direct dependencies instead of peer deps). I then decided to make Babel and React peer deps so that end users could have more control over their code.

Ideally, both would be possible! I'd love for it to Just Work ™️ without any configuration, but also allow for deeper control for end users that would like to have it.

Some ideas:
1. Have defaults  under the hood (even with `preset-env`'s `targets`), but expose some configuration options (`targets`, plugins, presets).
2. The `babelConfig()` callback could be called with the default babel config that's generated, allowing users to customize it to their liking before returning the mutated config which the plugin will use (I _think_ this is my preference)?

We might always want to have a `targets` configuration API anyway, since different projects have different browser support needs.

**Comment by dpfavand** [comment]
Re targets: A lot of projects use [browserlist](https://www.npmjs.com/package/browserslist), which can be defined in a project-specific config file, or even as the project's `package.json`. Would it make sense to hook into this to allow users to define their project's targets?

I also think I prefer option 2. If someone has a complex enough setup to require a custom babel config, it's probably easier to give them full control over it rather than exposing only certain options.

Another thought - should we somehow be hooking into .babelrc or babel.config.js? I suppose it would be easy enough for the user to import the config to their custom babelConfig() callback if they needed to.

**Comment by dpfavand** [comment]
Given how simple TSX support appears to be, would it be good to have `@babel/preset-typescript` part of a "sane default" Babel config? Even further, if extensions are configurable (#13), we could test if `tsx` is in the list of extensions and add it to the Babel config.

Downside is that including `@babel/preset-typescript` in peer deps might cause it to be added to a lot of projects that don't need it. I don't know if that's a bad trade-off for a pretty simple sane-default "it just works" Typescript experience.

**Comment by kaicataldo** [comment]
Yeah, I think so. I'm all for making everything just work out of the box, and am thinking I'll rewrite things so that it does just that.

The tricky part about having both defaults and customization is the different locations for `node_modules` - i.e. Babel will have to resolve some plugins and presets from `node_modules/` and some from `node_modules/eleventy-plugin-react/node_modules/`.

That being said, I've fallen in the trap here of not optimizing for the happy path (sane defaults with the ability to specify `targets` for the client-side code) that 90% of people will use and instead wanted to make sure it supported everyone, at the detriment of DX for the 90%.

**Comment by kaicataldo** [comment]
Okay, so here's a WIP PR on everything just working out of the box (no configuration required). If you have any feedback, it's definitely welcome! https://github.com/kaicataldo/eleventy-plugin-react/pull/15

The API for modifying the Babel config isn't super robust yet (it pushes any presets/plugins to their respective arrays in the default config), but I figured it's best to start from the "happy path" of 0 config, and add features as needed for cases that stray from that path.

**Comment by kaicataldo** [comment]
https://github.com/kaicataldo/eleventy-plugin-react/pull/15 has been merged, so this is done! I'm going to open another issue to make a preset so that the end user doesn't need to install all these peer deps (just the preset).

**Comment by kaicataldo** [comment]
Reopening because I ended up reverted #15 due to a regression. Will revisit ASAP.

**Comment by kaicataldo** [comment]
This should now be fixed by https://github.com/kaicataldo/eleventy-plugin-react/commit/51282590917081962d8b4a3ef5eb1e2d412a2f30!
